name: map_launcher
description: Map Launcher is a flutter plugin to find available maps installed on a device and launch them with a marker or show directions.
version: 3.1.0
homepage: https://github.com/mattermoran/map_launcher

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.alexmiller.map_launcher
        pluginClass: MapLauncherPlugin
      ios:
        pluginClass: MapLauncherPlugin

  assets:
    - assets/icons/

screenshots:
  - description: 'Show marker demo'
    path: screenshots/marker.webp
  - description: 'Show directions demo'
    path: screenshots/directions.webp
